// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeGvtILVDfnvteESAlbEMK4kVlpwJbdAU',
    appId: '1:381969372251:web:5bad96aac069e582a2db7e',
    messagingSenderId: '381969372251',
    projectId: 'biss-to-cli-for-cli',
    authDomain: 'biss-to-cli-for-cli.firebaseapp.com',
    storageBucket: 'biss-to-cli-for-cli.appspot.com',
    measurementId: 'G-H7WJ1MD6F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJ34UOl-wJKepaWY7v9pySgDyc5PplBo',
    appId: '1:381969372251:android:32352c1b3ee23ceca2db7e',
    messagingSenderId: '381969372251',
    projectId: 'biss-to-cli-for-cli',
    storageBucket: 'biss-to-cli-for-cli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1SOOGipQmgO9LX938P9dd-QU92P4KRvE',
    appId: '1:381969372251:ios:f415842d15ef3472a2db7e',
    messagingSenderId: '381969372251',
    projectId: 'biss-to-cli-for-cli',
    storageBucket: 'biss-to-cli-for-cli.appspot.com',
    iosBundleId: 'com.example.b2clientsForClients',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1SOOGipQmgO9LX938P9dd-QU92P4KRvE',
    appId: '1:381969372251:ios:f415842d15ef3472a2db7e',
    messagingSenderId: '381969372251',
    projectId: 'biss-to-cli-for-cli',
    storageBucket: 'biss-to-cli-for-cli.appspot.com',
    iosBundleId: 'com.example.b2clientsForClients',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeGvtILVDfnvteESAlbEMK4kVlpwJbdAU',
    appId: '1:381969372251:web:3c1230c1679cb558a2db7e',
    messagingSenderId: '381969372251',
    projectId: 'biss-to-cli-for-cli',
    authDomain: 'biss-to-cli-for-cli.firebaseapp.com',
    storageBucket: 'biss-to-cli-for-cli.appspot.com',
    measurementId: 'G-ZVFNGWLQK5',
  );
}
